### ISSUE TITLE
编译Pod失败了。

### ISSUE THREAD

**Issue by yinjiahjk** [FlutterPrograms/FlutterPrograms#3]
提示没有.ios目录，最新的flutter版本。请问有办法吗？

**Comment by yinjiahjk** [comment]
[!] Invalid `Podfile` file: No such file or directory @ rb_sysopen - ../../flutter_module/.ios/Flutter/podhelper.rb.

 #  from /Users/hyc/Desktop/FlutterPrograms/iOS/FlutterPrograms/Podfile:6
 #  -------------------------------------------
 #  flutter_application_path = '../../flutter_module'
 >  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
 #  
 #  -------------------------------------------

[!] Smart quotes were detected and ignored in your Podfile. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.

**Comment by amisare** [comment]
我这里需要更多的信息：
1.更为详细的操作步骤
2.flutter 版本号？
3.终端错误截图

**Comment by bill-zm** [comment]
<img width="588" alt="WechatIMG20" src="https://user-images.githubusercontent.com/11487305/59745157-c642be00-92a6-11e9-97c7-47b0c63b6b82.png">
<img width="766" alt="WechatIMG19" src="https://user-images.githubusercontent.com/11487305/59745161-c80c8180-92a6-11e9-8ad8-95acba4e16e0.png">


提示没有.ios目录  flutter1.0.0 请问有办法吗？

**Comment by amisare** [comment]
pod install 依赖 flutter_module 下的资源，按以下步骤尝试解决：
- 新建终端，进入 `flutter_module` 目录
- 终端执行 `flutter packages get` ，加载依赖包
- 新建终端，进入 `iOS/FlutterPrograms` 目录 ，执行 `pod install` 。
