### ISSUE TITLE
用JIT上不了APP store吧

### ISSUE THREAD

**Issue by cheniosc** [FlutterPrograms/FlutterPrograms#4]

**Comment by amisare** [comment]
Flutter 的 JIT 和 AOT 本质上又有什么区别那？

**Comment by chenxijun1992** [comment]
> Flutter 的 JIT 和 AOT 本质上又有什么区别那？

本质上是没什么区别。这种JIT模式，苹果应该能查出来，2种模式的APP.framework不一样

**Comment by amisare** [comment]
JIT 中不需要 APP.framework 。
